### ISSUE TITLE
Compatibility Issue with @solidjs/router Version "^0.12.4" and @tma.js/solid-router-integration

### ISSUE THREAD

**Issue by Shoyadbek** [Telegram-Mini-Apps/solidjs-template#1]
Hello,

I recently encountered a compatibility issue while integrating @tma.js/solid-router-integration with @solidjs/router. I noticed that with @solidjs/router version "^0.12.4", the application threw an error related to the export named 'createIntegration' not being found. This error was:

`Uncaught SyntaxError: The requested module '/node_modules/@solidjs/router/dist/index.jsx' does not provide an export named 'createIntegration'`

After some investigation and testing, I found that the issue does not occur with an older version of @solidjs/router, specifically version "^0.8.3". Switching to this version resolved the problem, and the integration worked as expected.

**Steps to Reproduce**

Install @solidjs/router version "^0.12.4" and @tma.js/solid-router-integration.
Attempt to use createIntegration from @tma.js/solid-router-integration as per the documentation.
Observe the error in the console when trying to run the application.

**Solution**
I resolved the issue by downgrading @solidjs/router to version "^0.8.3". Here is the dependency version that worked:

`"@solidjs/router": "0.8.3",`

**Suggestion**
It might be beneficial for others who face the same issue to have a note or warning about this specific version compatibility in the documentation. Additionally, it would be great if future versions could ensure compatibility or provide guidance on integrating with @tma.js/solid-router-integration.

Thank you for your work on these libraries. They are valuable tools for the SolidJS community. I hope this information helps improve compatibility and assists others facing similar issues.

Best regards

**Comment by heyqbnk** [comment]
Oh, I am so sorry, I didn't see your issue. I have updated the template removing integration package. It will be reworked further. Could you take a look on the current template state and check if it fits you?
