### ISSUE TITLE
Is there a way to prevent backButton default novaigation on click

### ISSUE THREAD

**Issue by nomercy360** [Telegram-Mini-Apps/solidjs-template#2]
There are some pages in my app where i want to redirect to home instead and clear the history (show close button). Router mechanic prevents from it - it always pushing back. Can i somehow disable default behaviour?

```
// route history was like /profile/edit/1step -> /profile/edit/2step -> /profile/[id]
// if i click backbutton it will push back to form step2, but i dont want this.
// i tried to explicitly specify on click action, but history saves anyway and router will push to form again if user clicks back button
  const navigate = useNavigate();
  
  const navigateHome = () => {
    navigate('/');
  }

  backButton().on('click', navigateHome);
  ```
  
  Should redirect home and not showing backbutton

**Comment by heyqbnk** [comment]
Hey! 

What I see here, is you are not clearing the history, but adding a new item to it. In other words, you are adding a new item with path `/`. As long as history is not empty, you will still see the `BackButton`.

You could probably implement the functionality you want, using some kind of this code:

```js
const navigate = useNavigate();

// You have to write your own hook to retrieve current
// navigator. We are creating it in the App component.
// There, you could place your context provider and pass
// created navigator.
const navigator = useNavigator();
  
const navigateHome = () => {
  navigate(-navigator.cursor);
  navigate('/', { replace: true });
}

backButton().on('click', navigateHome);
```

So, the idea behind it is you know current navigation history cursor. You are going back by this cursor and replacing a history entry with a new item (`/`) if required.

I am preparing @tma.js/sdk@3.0 solving some of these issues. Will be released soon
